Repository SMU-25/server, pull requests merged in 2025-08, with the labels that each got.

#169 🐛 [FIX] 캘린더 오타 수정
  src/main/java/final_project/momeasy/domain/calendar/entity/Calendar.java
Labels: 🐞 BugFix

#171 :hammer: [REFACTOR] HomecamUpdateDTO에 serial_num 제거
  src/main/java/final_project/momeasy/domain/home_cam/dto/HomecamRequestDTO.java
Labels: 🔨 Refactor

#173 🐛 [FIX] 매핑 수정으로 캘린더 500 오류 해결
  src/main/java/final_project/momeasy/domain/calendar/controller/CalendarController.java
  src/main/java/final_project/momeasy/domain/calendar/converter/CalendarConverter.java
  src/main/java/final_project/momeasy/domain/calendar/dto/CalendarRequestDto.java
  src/main/java/final_project/momeasy/domain/calendar/dto/CalendarResponseDto.java
  src/main/java/final_project/momeasy/domain/calendar/entity/Calendar.java
  src/main/java/final_project/momeasy/domain/calendar/repository/CalendarRepository.java
  src/main/java/final_project/momeasy/domain/calendar/service/CalendarQueryService.java
  src/main/java/final_project/momeasy/domain/calendar/service/CalendarService.java
Labels: 🐞 BugFix

#175 ✨ [FEAT] 홈캠 그래프 조회 기능 추가
  src/main/java/final_project/momeasy/domain/fever_graph/dto/FeverGraphResponseDTO.java
  src/main/java/final_project/momeasy/domain/fever_graph/service/FeverGraphService.java
  src/main/java/final_project/momeasy/domain/fever_graph/service/FeverGraphServiceImpl.java
  src/main/java/final_project/momeasy/domain/home_cam/controller/HomecamController.java
  src/main/java/final_project/momeasy/domain/home_cam/converter/HomecamConverter.java
  src/main/java/final_project/momeasy/domain/home_cam/dto/HomecamResponseDTO.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamQueryService.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/humidity_graph/dto/HumidityGraphResponseDTO.java
  src/main/java/final_project/momeasy/domain/humidity_graph/service/HumidityGraphService.java
  src/main/java/final_project/momeasy/domain/humidity_graph/service/HumidityGraphServiceImpl.java
  src/main/java/final_project/momeasy/domain/temperature_graph/dto/TemperatureGraphResponseDTO.java
  src/main/java/final_project/momeasy/domain/temperature_graph/service/TemperatureGraphService.java
  src/main/java/final_project/momeasy/domain/temperature_graph/service/TemperatureGraphServiceImpl.java
Labels: ✨ Feature

#177 ✨ [FEAT] FCM 알림 인프라 구축
  src/main/java/final_project/momeasy/common/enums/DeviceType.java
  src/main/java/final_project/momeasy/global/config/AsyncConfig.java
  src/main/java/final_project/momeasy/global/fcm/controller/FcmTokenController.java
  src/main/java/final_project/momeasy/global/fcm/dto/FcmTokenRequest.java
  src/main/java/final_project/momeasy/global/fcm/entity/FcmToken.java
  src/main/java/final_project/momeasy/global/fcm/exception/FcmErrorCode.java
  src/main/java/final_project/momeasy/global/fcm/exception/FcmException.java
  src/main/java/final_project/momeasy/global/fcm/repository/FcmTokenRepository.java
  src/main/java/final_project/momeasy/global/fcm/service/FcmService.java
  src/main/java/final_project/momeasy/global/fcm/service/FcmTokenService.java
Labels: ✨ Feature

#182 🔨 [REFACTOR] Firebase 라이브러리 해결
  build.gradle
Labels: 🔨 Refactor

#186 🐛 [FIX] ErrorCode 임포트 제거 및 MessagingErrorCode로 변경
  src/main/java/final_project/momeasy/common/enums/DeviceType.java
  src/main/java/final_project/momeasy/global/config/AsyncConfig.java
  src/main/java/final_project/momeasy/global/fcm/controller/FcmTokenController.java
  src/main/java/final_project/momeasy/global/fcm/dto/FcmTokenRequest.java
  src/main/java/final_project/momeasy/global/fcm/entity/FcmToken.java
  src/main/java/final_project/momeasy/global/fcm/exception/FcmErrorCode.java
  src/main/java/final_project/momeasy/global/fcm/exception/FcmException.java
  src/main/java/final_project/momeasy/global/fcm/repository/FcmTokenRepository.java
  src/main/java/final_project/momeasy/global/fcm/service/FcmService.java
  src/main/java/final_project/momeasy/global/fcm/service/FcmTokenService.java
Labels: 🐞 BugFix

#187 🔨 [REFACTOR] Notification 연관관계/푸시 로직 정리
  src/main/java/final_project/momeasy/domain/notification/converter/NotificationConverter.java
  src/main/java/final_project/momeasy/domain/notification/service/NotificationServiceImpl.java
  src/main/java/final_project/momeasy/domain/parent/entity/Parent.java
Labels: 🔨 Refactor
