Repository SMU-25/server, pull requests merged in 2025-05, with the labels that each got.

#2 :sparkles: [Feat] 도메인 관련 엔티티 생성
  src/main/java/final_project/momeasy/common/enums/Gender.java
  src/main/java/final_project/momeasy/common/enums/IllnessType.java
  src/main/java/final_project/momeasy/common/enums/Relation.java
  src/main/java/final_project/momeasy/common/enums/Seizure.java
  src/main/java/final_project/momeasy/common/enums/SymptomType.java
  src/main/java/final_project/momeasy/domain/calendar/entity/Calendar.java
  src/main/java/final_project/momeasy/domain/child/entity/Child.java
  src/main/java/final_project/momeasy/domain/child/entity/ChildIllness.java
  src/main/java/final_project/momeasy/domain/fever_record/entity/FeverRecord.java
  src/main/java/final_project/momeasy/domain/fever_report/entity/FeverReport.java
  src/main/java/final_project/momeasy/domain/fever_report/entity/FeverReportSymptom.java
  src/main/java/final_project/momeasy/domain/home_cam/entity/Homecam.java
  src/main/java/final_project/momeasy/domain/illness/entity/Illness.java
  src/main/java/final_project/momeasy/domain/notification/entity/Notification.java
  src/main/java/final_project/momeasy/domain/outing_record/entity/OutingRecord.java
  src/main/java/final_project/momeasy/domain/parent/entity/Parent.java
  src/main/java/final_project/momeasy/domain/parent/entity/ParentChild.java
  src/main/java/final_project/momeasy/domain/room_condition/entity/RoomCondition.java
  src/main/java/final_project/momeasy/domain/setting/entity/Setting.java
  src/main/java/final_project/momeasy/domain/symptom/entity/Symptom.java
  src/main/java/final_project/momeasy/global/entity/BaseEntity.java
  src/main/java/final_project/momeasy/global/entity/Email.java
Labels: ✨ Feature

#4 :sparkles: [Feat] 리포지터리 구현
  src/main/java/final_project/momeasy/domain/calendar/repository/CalendarRepository.java
  src/main/java/final_project/momeasy/domain/child/repository/ChildRepository.java
  src/main/java/final_project/momeasy/domain/fever_record/repository/FeverRecordRepository.java
  src/main/java/final_project/momeasy/domain/fever_report/repository/FeverReportRepository.java
  src/main/java/final_project/momeasy/domain/home_cam/repository/HomecamRepository.java
  src/main/java/final_project/momeasy/domain/illness/repository/IllnessRepository.java
  src/main/java/final_project/momeasy/domain/notification/repository/NotificationRepository.java
  src/main/java/final_project/momeasy/domain/outing_record/repository/OutingRecordRepository.java
  src/main/java/final_project/momeasy/domain/parent/repository/ParentRepository.java
  src/main/java/final_project/momeasy/domain/room_condition/repository/RoomConditionRepository.java
  src/main/java/final_project/momeasy/domain/setting/repository/SettingRepository.java
  src/main/java/final_project/momeasy/domain/symptom/repository/SymptomRepository.java
  src/test/java/final_project/momeasy/domain/calendar/repository/CalendarRepositoryTest.java
  src/test/java/final_project/momeasy/domain/child/repository/ChildRepositoryTest.java
  src/test/java/final_project/momeasy/domain/fever_record/repository/FeverRecordRepositoryTest.java
  src/test/java/final_project/momeasy/domain/fever_report/repository/FeverReportRepositoryTest.java
  src/test/java/final_project/momeasy/domain/home_cam/repository/HomecamRepositoryTest.java
  src/test/java/final_project/momeasy/domain/illness/repository/IllnessRepositoryTest.java
  src/test/java/final_project/momeasy/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/final_project/momeasy/domain/outing_record/repository/OutingRecordRepositoryTest.java
  src/test/java/final_project/momeasy/domain/parent/repository/ParentRepositoryTest.java
  src/test/java/final_project/momeasy/domain/room_condition/repository/RoomConditionRepositoryTest.java
  src/test/java/final_project/momeasy/domain/setting/repository/SettingRepositoryTest.java
  src/test/java/final_project/momeasy/domain/symptom/repository/SymptomRepositoryTest.java
Labels: ✨ Feature

#6 [Feat] 응답 통일, 예외 처리
  src/main/java/final_project/momeasy/domain/calendar/exception/CalendarErrorCode.java
  src/main/java/final_project/momeasy/domain/calendar/exception/CalendarException.java
  src/main/java/final_project/momeasy/domain/child/exception/ChildErrorCode.java
  src/main/java/final_project/momeasy/domain/child/exception/ChildException.java
  src/main/java/final_project/momeasy/domain/fever_record/exception/FeverRecordErrorCode.java
  src/main/java/final_project/momeasy/domain/fever_record/exception/FeverRecordException.java
  src/main/java/final_project/momeasy/domain/fever_report/exception/FeverReportErrorCode.java
  src/main/java/final_project/momeasy/domain/fever_report/exception/FeverReportException.java
  src/main/java/final_project/momeasy/domain/home_cam/exception/HomecamErrorCode.java
  src/main/java/final_project/momeasy/domain/home_cam/exception/HomecamException.java
  src/main/java/final_project/momeasy/domain/illness/exception/IllnessErrorCode.java
  src/main/java/final_project/momeasy/domain/illness/exception/IllnessException.java
  src/main/java/final_project/momeasy/domain/notification/exception/NotificationErrorCode.java
  src/main/java/final_project/momeasy/domain/notification/exception/NotificationException.java
  src/main/java/final_project/momeasy/domain/outing_record/exception/OutingRecordErrorCode.java
  src/main/java/final_project/momeasy/domain/outing_record/exception/OutingRecordException.java
  src/main/java/final_project/momeasy/domain/parent/exception/ParentErrorCode.java
  src/main/java/final_project/momeasy/domain/parent/exception/ParentException.java
  src/main/java/final_project/momeasy/domain/room_condition/exception/RoomConditionErrorCode.java
  src/main/java/final_project/momeasy/domain/room_condition/exception/RoomConditionException.java
  src/main/java/final_project/momeasy/domain/setting/exception/SettingErrorCode.java
  src/main/java/final_project/momeasy/domain/setting/exception/SettingException.java
  src/main/java/final_project/momeasy/domain/symptom/exception/SymptomErrorCode.java
  src/main/java/final_project/momeasy/domain/symptom/exception/SymptomException.java
  src/main/java/final_project/momeasy/global/apiPayload/CustomResponse.java
  src/main/java/final_project/momeasy/global/apiPayload/code/BaseErrorCode.java
  src/main/java/final_project/momeasy/global/apiPayload/code/GeneralErrorCode.java
  src/main/java/final_project/momeasy/global/apiPayload/exception/CustomException.java
  src/main/java/final_project/momeasy/global/apiPayload/exception/handler/GlobalExceptionHandler.java
Labels: ✨ Feature

#8 [Feat] 홈캠 Homecam 조회, 삭제, 생성 구현
  src/main/java/final_project/momeasy/domain/home_cam/controller/HomecamController.java
  src/main/java/final_project/momeasy/domain/home_cam/converter/HomecamConverter.java
  src/main/java/final_project/momeasy/domain/home_cam/dto/HomecamRequestDTO.java
  src/main/java/final_project/momeasy/domain/home_cam/dto/HomecamResponseDTO.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamQueryService.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamService.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamServiceImpl.java
Labels: ✨ Feature

#11 :hammer: [Refactor] 홈캠, 자식 관계 추가
  src/main/java/final_project/momeasy/domain/child/entity/Child.java
  src/main/java/final_project/momeasy/domain/home_cam/entity/Homecam.java
  src/test/java/final_project/momeasy/domain/home_cam/repository/HomecamRepositoryTest.java
Labels: 🔨 Refactor

#14 :sparkles: [Feat] 온습도 기록 조회, 삭제, 생성 구현
  src/main/java/final_project/momeasy/domain/room_condition/controller/RoomConditionController.java
  src/main/java/final_project/momeasy/domain/room_condition/converter/RoomConditionConverter.java
  src/main/java/final_project/momeasy/domain/room_condition/dto/RoomConditionRequestDTO.java
  src/main/java/final_project/momeasy/domain/room_condition/dto/RoomConditionResponseDTO.java
  src/main/java/final_project/momeasy/domain/room_condition/repository/RoomConditionRepository.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryService.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionService.java
Labels: ✨ Feature

#30 :hammer: [Refactor] OutingRecord Entity 삭제
  src/main/java/final_project/momeasy/domain/child/entity/Child.java
  src/main/java/final_project/momeasy/domain/outing_record/entity/OutingRecord.java
  src/main/java/final_project/momeasy/domain/outing_record/exception/OutingRecordErrorCode.java
  src/main/java/final_project/momeasy/domain/outing_record/exception/OutingRecordException.java
  src/main/java/final_project/momeasy/domain/outing_record/repository/OutingRecordRepository.java
Labels: 🔨 Refactor

#35 🚀 [Chore] 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/ISSUE_TEMPLATE/🔨-refactor.md
Labels: 📃 Docs

#40 ✨ [Feat] 카카오 로그인 구현
  build.gradle
  src/main/java/final_project/momeasy/common/enums/Gender.java
  src/main/java/final_project/momeasy/domain/parent/controller/ParentController.java
  src/main/java/final_project/momeasy/domain/parent/converter/ParentConverter.java
  src/main/java/final_project/momeasy/domain/parent/entity/Parent.java
  src/main/java/final_project/momeasy/domain/parent/exception/ParentErrorCode.java
  src/main/java/final_project/momeasy/global/auth/controller/AuthController.java
  src/main/java/final_project/momeasy/global/auth/dto/OAuthAttributes.java
  src/main/java/final_project/momeasy/global/auth/dto/ParentProfile.java
  src/main/java/final_project/momeasy/global/auth/exception/AuthErrorCode.java
  src/main/java/final_project/momeasy/global/auth/exception/AuthException.java
  src/main/java/final_project/momeasy/global/auth/service/CustomOAuthUserService.java
  src/main/java/final_project/momeasy/global/config/SecurityConfig.java
  src/main/java/final_project/momeasy/global/security/CustomUserDetailsService.java
  src/main/java/final_project/momeasy/global/security/filter/CustomLoginFilter.java
  src/main/java/final_project/momeasy/global/security/handler/OAuth2LoginSuccessHandler.java
  src/main/resources/application.yml
Labels: ✨ Feature

#44 ✨ [Feat] 카카오 로그인 및 버그 수정 merge (develop)
  build.gradle
  src/main/java/final_project/momeasy/common/enums/Gender.java
  src/main/java/final_project/momeasy/domain/parent/controller/ParentController.java
  src/main/java/final_project/momeasy/domain/parent/converter/ParentConverter.java
  src/main/java/final_project/momeasy/domain/parent/entity/Parent.java
  src/main/java/final_project/momeasy/domain/parent/exception/ParentErrorCode.java
  src/main/java/final_project/momeasy/global/auth/controller/AuthController.java
  src/main/java/final_project/momeasy/global/auth/dto/OAuthAttributes.java
  src/main/java/final_project/momeasy/global/auth/dto/ParentProfile.java
  src/main/java/final_project/momeasy/global/auth/exception/AuthErrorCode.java
  src/main/java/final_project/momeasy/global/auth/exception/AuthException.java
  src/main/java/final_project/momeasy/global/auth/service/CustomOAuthUserService.java
  src/main/java/final_project/momeasy/global/config/SecurityConfig.java
  src/main/java/final_project/momeasy/global/security/CustomUserDetailsService.java
  src/main/java/final_project/momeasy/global/security/filter/CustomLoginFilter.java
  src/main/java/final_project/momeasy/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/final_project/momeasy/global/security/handler/OAuth2LoginSuccessHandler.java
  src/main/resources/application.yml
Labels: ✨ Feature

#47 :bug: [FIX] @AuthenticationPrincipal parent에 null 담기는 현상
  src/main/java/final_project/momeasy/domain/fever_report/controller/FeverReportController.java
  src/main/java/final_project/momeasy/domain/home_cam/controller/HomecamController.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamService.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamServiceImpl.java
Labels: 🐞 BugFix
