Repository SMU-25/server, pull requests merged in 2025-07, with the labels that each got.

#90 ✨ [FEAT] 현재 시각 기준 그래프 조회
  src/main/java/final_project/momeasy/domain/fever_record/controller/FeverRecordController.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordQueryService.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/room_condition/controller/RoomConditionController.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryService.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryServiceImpl.java
Labels: ✨ Feature

#91 ✨ [Feat] 홈캠이 켜질 때 스트리밍 주소를 video_url에 저장
  src/main/java/final_project/momeasy/domain/home_cam/entity/Homecam.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamServiceImpl.java
Labels: ✨ Feature

#93 📝 [DOCS] 이슈/pr 템플릿 수정
  .github/ISSUE_TEMPLATE/🐛-fix.md
  .github/ISSUE_TEMPLATE/📝-docs.md
  .github/ISSUE_TEMPLATE/🤍-ci-cd.md
  .github/ISSUE_TEMPLATE/🧪-test.md
  .github/pull_request_template.md
Labels: 📃 Docs

#95 🤍 [CI] ci/cd 설정
  .github/workflows/cicd.yml
  Dockerfile
  build.gradle
  src/main/resources/application.yml
Labels: 🌏 Deploy

#99 🐛 Fix: ec2에 redis 설정
  src/main/resources/application.yml
Labels: 🐞 BugFix

#101 :bug: [FIX] ec2 서버에서 모든 ip 소켓 통신 허용
  src/main/java/final_project/momeasy/global/tcp/TcpServer.java
Labels: ✨ Feature

#103 :bug: [FIX] docker에서 12345 port 허용
  .github/workflows/cicd.yml
Labels: 🐞 BugFix

#105 🔨 [REFACTOR] 예외 처리, 최근 발열 조회 리팩토링
  src/main/java/final_project/momeasy/domain/fever_record/repository/FeverRecordRepository.java
  src/main/java/final_project/momeasy/domain/fever_report/exception/FeverReportErrorCode.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamServiceImpl.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryServiceImpl.java
Labels: 🔨 Refactor

#106 ✨ [FEAT] Flutter용 소셜 로그인(kakao/naver) API 추가
  src/main/java/final_project/momeasy/common/enums/SocialType.java
  src/main/java/final_project/momeasy/domain/token/repository/TokenRepository.java
  src/main/java/final_project/momeasy/domain/token/service/TokenService.java
  src/main/java/final_project/momeasy/global/auth/client/KakaoOAuthApiClient.java
  src/main/java/final_project/momeasy/global/auth/client/NaverOAuthApiClient.java
  src/main/java/final_project/momeasy/global/auth/client/SocialOAuthApiClient.java
  src/main/java/final_project/momeasy/global/auth/controller/AuthController.java
  src/main/java/final_project/momeasy/global/auth/dto/request/OAuthRequestDTO.java
  src/main/java/final_project/momeasy/global/auth/dto/response/OAuthResponseDTO.java
  src/main/java/final_project/momeasy/global/auth/service/OAuthLoginService.java
  src/main/java/final_project/momeasy/global/auth/service/OAuthLoginServiceImpl.java
  src/main/java/final_project/momeasy/global/config/AppConfig.java
  src/main/java/final_project/momeasy/global/config/SecurityConfig.java
Labels: ✨ Feature

#109 ✨ [FEAT] 커서 페이지네이션 추가
  src/main/java/final_project/momeasy/domain/fever_record/controller/FeverRecordController.java
  src/main/java/final_project/momeasy/domain/fever_record/converter/FeverRecordConverter.java
  src/main/java/final_project/momeasy/domain/fever_record/dto/FeverRecordResponseDTO.java
  src/main/java/final_project/momeasy/domain/fever_record/repository/FeverRecordRepository.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordQueryService.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/fever_report/controller/FeverReportController.java
  src/main/java/final_project/momeasy/domain/fever_report/converter/FeverReportConverter.java
  src/main/java/final_project/momeasy/domain/fever_report/dto/FeverReportResponseDTO.java
  src/main/java/final_project/momeasy/domain/fever_report/repository/FeverReportRepository.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportQueryService.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/home_cam/controller/HomecamController.java
  src/main/java/final_project/momeasy/domain/room_condition/controller/RoomConditionController.java
  src/main/java/final_project/momeasy/domain/room_condition/converter/RoomConditionConverter.java
  src/main/java/final_project/momeasy/domain/room_condition/dto/RoomConditionResponseDTO.java
  src/main/java/final_project/momeasy/domain/room_condition/repository/RoomConditionRepository.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryService.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryServiceImpl.java
  src/main/java/final_project/momeasy/global/apiPayload/code/GeneralErrorCode.java
  src/main/java/final_project/momeasy/global/validation/annoation/CheckCursor.java
  src/main/java/final_project/momeasy/global/validation/annoation/CheckSize.java
  src/main/java/final_project/momeasy/global/validation/validator/CheckCursorValidator.java
  src/main/java/final_project/momeasy/global/validation/validator/CheckSizeValidator.java
Labels: ✨ Feature

#111 🐛 [FIX] 페이지네이션 초기값 설정 누락
  src/main/java/final_project/momeasy/domain/fever_record/controller/FeverRecordController.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/fever_report/controller/FeverReportController.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/room_condition/controller/RoomConditionController.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryServiceImpl.java
Labels: 🐞 BugFix

#113 ✨ [FEAT] feverReport 응답 DTO에 id 추가
  src/main/java/final_project/momeasy/domain/fever_report/converter/FeverReportConverter.java
  src/main/java/final_project/momeasy/domain/fever_report/dto/FeverReportResponseDTO.java
Labels: ✨ Feature

#119 🔨 [REFACTOR] 홈캠 생성,수정 방식 변경, DTO 변경
  src/main/java/final_project/momeasy/domain/home_cam/controller/HomecamController.java
  src/main/java/final_project/momeasy/domain/home_cam/converter/HomecamConverter.java
  src/main/java/final_project/momeasy/domain/home_cam/dto/HomecamRequestDTO.java
  src/main/java/final_project/momeasy/domain/home_cam/dto/HomecamResponseDTO.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamService.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamServiceImpl.java
Labels: 🔨 Refactor

#121 ✨ [FEAT] 마이페이지 회원 정보 조회 및 수정
  src/main/java/final_project/momeasy/domain/parent/controller/ParentController.java
  src/main/java/final_project/momeasy/domain/parent/converter/ParentConverter.java
  src/main/java/final_project/momeasy/domain/parent/dto/request/ParentRequestDTO.java
  src/main/java/final_project/momeasy/domain/parent/dto/response/ParentResponseDTO.java
  src/main/java/final_project/momeasy/domain/parent/entity/Parent.java
  src/main/java/final_project/momeasy/domain/parent/service/command/ParentCommandService.java
  src/main/java/final_project/momeasy/domain/parent/service/command/ParentCommandServiceImpl.java
  src/main/java/final_project/momeasy/domain/parent/service/query/ParentQueryService.java
  src/main/java/final_project/momeasy/domain/parent/service/query/ParentQueryServiceImpl.java
  src/main/java/final_project/momeasy/global/auth/exception/AuthErrorCode.java
Labels: ✨ Feature

#122 ✨ [FEAT] 프로필 이미지 저장 (S3 이용)
  build.gradle
  src/main/java/final_project/momeasy/domain/parent/controller/ParentController.java
  src/main/java/final_project/momeasy/domain/parent/entity/Parent.java
  src/main/java/final_project/momeasy/domain/parent/exception/ParentErrorCode.java
  src/main/java/final_project/momeasy/domain/parent/service/command/ParentCommandService.java
  src/main/java/final_project/momeasy/domain/parent/service/command/ParentCommandServiceImpl.java
  src/main/java/final_project/momeasy/global/config/S3Config.java
  src/main/java/final_project/momeasy/global/util/s3/S3Uploader.java
  src/main/resources/application.yml
Labels: ✨ Feature

#73 ✨ [FEAT] CalendarController 생성 및 캘린더 기능 API 구현
  src/main/java/final_project/momeasy/domain/calendar/controller/CalendarController.java
  src/main/java/final_project/momeasy/domain/calendar/converter/CalendarConverter.java
  src/main/java/final_project/momeasy/domain/calendar/dto/CalendarRequestDto.java
  src/main/java/final_project/momeasy/domain/calendar/dto/CalendarResponseDto.java
  src/main/java/final_project/momeasy/domain/calendar/entity/Calendar.java
  src/main/java/final_project/momeasy/domain/calendar/exception/CalendarErrorCode.java
  src/main/java/final_project/momeasy/domain/calendar/repository/CalendarRepository.java
  src/main/java/final_project/momeasy/domain/calendar/service/CalendarQueryService.java
  src/main/java/final_project/momeasy/domain/calendar/service/CalendarService.java
  src/main/java/final_project/momeasy/domain/illness/config/IllnessInitializer.java
  src/main/java/final_project/momeasy/domain/illness/controller/IllnessController.java
  src/main/java/final_project/momeasy/domain/illness/converter/IllnessConverter.java
  src/main/java/final_project/momeasy/domain/illness/dto/IllnessResponse.java
  src/main/java/final_project/momeasy/domain/illness/entity/Illness.java
  src/main/java/final_project/momeasy/domain/illness/repository/IllnessRepository.java
  src/main/java/final_project/momeasy/domain/illness/service/IllnessService.java
  src/main/java/final_project/momeasy/domain/symptom/config/SymptomInitializer.java
  src/main/java/final_project/momeasy/domain/symptom/controller/SymptomController.java
  src/main/java/final_project/momeasy/domain/symptom/converter/SymptomConverter.java
  src/main/java/final_project/momeasy/domain/symptom/dto/SymptomResponse.java
  src/main/java/final_project/momeasy/domain/symptom/entity/Symptom.java
  src/main/java/final_project/momeasy/domain/symptom/exception/SymptomErrorCode.java
  src/main/java/final_project/momeasy/domain/symptom/service/SymptomService.java
Labels: ✨ Feature

#125 🐛 [FIX] Symptom 필드명 통일
  src/main/java/final_project/momeasy/domain/symptom/config/SymptomInitializer.java
  src/main/java/final_project/momeasy/domain/symptom/converter/SymptomConverter.java
  src/main/java/final_project/momeasy/domain/symptom/entity/Symptom.java
Labels: 🐞 BugFix

#127 🔨 Refactor: token expiration 환경변수로 변경
  src/main/resources/application.yml
Labels: 🔨 Refactor

#140 :bug: [FIX] 발열 리포트 오타 수정
  src/main/java/final_project/momeasy/domain/fever_report/repository/FeverReportRepository.java
Labels: 🐞 BugFix

#141 ✨ [FEAT] 비밀번호 재설정
  src/main/java/final_project/momeasy/global/auth/controller/AuthController.java
  src/main/java/final_project/momeasy/global/auth/dto/request/OAuthRequestDTO.java
  src/main/java/final_project/momeasy/global/auth/exception/AuthErrorCode.java
  src/main/java/final_project/momeasy/global/auth/service/PasswordResetService.java
  src/main/java/final_project/momeasy/global/util/mail/service/MailService.java
  src/main/java/final_project/momeasy/global/util/mail/service/MailServiceImpl.java
Labels: ✨ Feature

#138 :sparkles: [FEAT] 발열 리포트 상세 조회에 illness 추가
  src/main/java/final_project/momeasy/domain/fever_report/converter/FeverReportConverter.java
  src/main/java/final_project/momeasy/domain/fever_report/dto/FeverReportResponseDTO.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportServiceImpl.java
Labels: ✨ Feature

#145 ✨ [Feat] 발열 리포트 AI 추가
  build.gradle
  src/main/java/final_project/momeasy/domain/fever_report/entity/FeverReport.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportServiceImpl.java
  src/main/java/final_project/momeasy/global/ai/SummaryAiService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#153 🐛 Fix: 마이페이지 내 정보 조회 시 프로필 이미지도 함께 조회하도록 수정
  src/main/java/final_project/momeasy/domain/parent/converter/ParentConverter.java
  src/main/java/final_project/momeasy/domain/parent/dto/response/ParentResponseDTO.java
Labels: 🐞 BugFix

#136 ✨ [FEAT] Notification 도메인 기능 구현
  src/main/java/final_project/momeasy/common/enums/NotificationType.java
  src/main/java/final_project/momeasy/domain/notification/controller/NotificationController.java
  src/main/java/final_project/momeasy/domain/notification/converter/NotificationConverter.java
  src/main/java/final_project/momeasy/domain/notification/dto/NotificationRequest.java
  src/main/java/final_project/momeasy/domain/notification/dto/NotificationResponse.java
  src/main/java/final_project/momeasy/domain/notification/entity/Notification.java
  src/main/java/final_project/momeasy/domain/notification/repository/NotificationRepository.java
  src/main/java/final_project/momeasy/domain/notification/service/NotificationService.java
  src/main/java/final_project/momeasy/domain/notification/service/NotificationServiceImpl.java
  src/main/java/final_project/momeasy/global/apiPayload/CursorResponse.java
Labels: ✨ Feature

#154 🐛 Fix: 인증 후 로그아웃 가능하도록 수정
  src/main/java/final_project/momeasy/global/security/handler/CustomLogoutHandler.java
Labels: 🐞 BugFix

#158 🐛 [FIX] NotificationServiceImpl - FCMToken 코드 구현 보류
  src/main/java/final_project/momeasy/domain/notification/service/NotificationServiceImpl.java
Labels: 🐞 BugFix

#163 ✨ [FEAT] 아이 이미지 등록 및 조회
  src/main/java/final_project/momeasy/domain/child/controller/ChildController.java
  src/main/java/final_project/momeasy/domain/child/converter/ChildConverter.java
  src/main/java/final_project/momeasy/domain/child/dto/request/ChildRequestDTO.java
  src/main/java/final_project/momeasy/domain/child/entity/Child.java
  src/main/java/final_project/momeasy/domain/child/service/command/ChildCommandService.java
  src/main/java/final_project/momeasy/domain/child/service/command/ChildCommandServiceImpl.java
  src/main/java/final_project/momeasy/domain/child/service/query/ChildQueryServiceImpl.java
Labels: ✨ Feature

#164 🔨 [REFACTOR] 아이 생성/추가 로직과 아이 프로필 이미지 추가 로직 분리
  src/main/java/final_project/momeasy/domain/child/controller/ChildController.java
  src/main/java/final_project/momeasy/domain/child/service/command/ChildCommandService.java
  src/main/java/final_project/momeasy/domain/child/service/command/ChildCommandServiceImpl.java
  src/main/java/final_project/momeasy/domain/child/service/query/ChildQueryServiceImpl.java
Labels: 🔨 Refactor
