Repository SMU-25/server, pull requests merged in 2025-06, with the labels that each got.

#49 ✨ [Feat] 네이버 로그인 구현 merge (develop)
  src/main/java/final_project/momeasy/global/auth/controller/AuthController.java
  src/main/java/final_project/momeasy/global/auth/dto/OAuthAttributes.java
  src/main/java/final_project/momeasy/global/auth/service/CustomOAuthUserService.java
  src/main/java/final_project/momeasy/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature

#53 :hammer: [Refactor] 홈캠, 발열 리포트, 온습도 기록, 체온 기록 created_at 변경
  src/main/java/final_project/momeasy/domain/fever_record/converter/FeverRecordConverter.java
  src/main/java/final_project/momeasy/domain/fever_record/dto/FeverRecordResponseDTO.java
  src/main/java/final_project/momeasy/domain/fever_report/converter/FeverReportConverter.java
  src/main/java/final_project/momeasy/domain/fever_report/dto/FeverReportResponseDTO.java
  src/main/java/final_project/momeasy/domain/home_cam/converter/HomecamConverter.java
  src/main/java/final_project/momeasy/domain/home_cam/dto/HomecamRequestDTO.java
  src/main/java/final_project/momeasy/domain/home_cam/dto/HomecamResponseDTO.java
  src/main/java/final_project/momeasy/domain/home_cam/entity/Homecam.java
  src/main/java/final_project/momeasy/domain/room_condition/converter/RoomConditionConverter.java
  src/main/java/final_project/momeasy/domain/room_condition/dto/RoomConditionResponseDTO.java
Labels: 🔨 Refactor

#54 ✨ [Feat] Service 예외 처리 추가, @AuthParent 추가
  src/main/java/final_project/momeasy/domain/fever_record/controller/FeverRecordController.java
  src/main/java/final_project/momeasy/domain/fever_record/repository/FeverRecordRepository.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordQueryService.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordService.java
  src/main/java/final_project/momeasy/domain/fever_report/controller/FeverReportController.java
  src/main/java/final_project/momeasy/domain/fever_report/repository/FeverReportRepository.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportQueryService.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportServiceImpl.java
  src/main/java/final_project/momeasy/domain/home_cam/controller/HomecamController.java
  src/main/java/final_project/momeasy/domain/home_cam/exception/HomecamErrorCode.java
  src/main/java/final_project/momeasy/domain/home_cam/repository/HomecamRepository.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamServiceImpl.java
  src/main/java/final_project/momeasy/domain/room_condition/controller/RoomConditionController.java
  src/main/java/final_project/momeasy/domain/room_condition/repository/RoomConditionRepository.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryService.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionService.java
  src/main/java/final_project/momeasy/global/config/WebConfig.java
  src/main/java/final_project/momeasy/global/config/resolver/AuthParentArgumentResolver.java
  src/main/java/final_project/momeasy/global/security/annotation/AuthParent.java
  src/test/java/final_project/momeasy/domain/outing_record/repository/OutingRecordRepositoryTest.java
Labels: ✨ Feature

#56 ✨ [FEAT] Scheduler 성능 향상
  src/main/java/final_project/momeasy/domain/child/repository/ChildRepository.java
  src/main/java/final_project/momeasy/domain/fever_record/repository/FeverRecordBulkRepository.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordService.java
  src/main/java/final_project/momeasy/domain/room_condition/repository/RoomConditionBulkRepository.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#59 🔨 [REFACTOR] 온습도, 체온 기록 전체 조회 삭제, 조회 created_at desc 정렬
  src/main/java/final_project/momeasy/domain/fever_record/controller/FeverRecordController.java
  src/main/java/final_project/momeasy/domain/fever_record/repository/FeverRecordRepository.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordQueryService.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/room_condition/controller/RoomConditionController.java
  src/main/java/final_project/momeasy/domain/room_condition/repository/RoomConditionRepository.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryService.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionQueryServiceImpl.java
Labels: 🔨 Refactor

#61 ✨ [FEAT] Child CRUD API 개발
  src/main/java/final_project/momeasy/common/enums/Gender.java
  src/main/java/final_project/momeasy/common/enums/Relation.java
  src/main/java/final_project/momeasy/domain/child/controller/ChildController.java
  src/main/java/final_project/momeasy/domain/child/converter/ChildConverter.java
  src/main/java/final_project/momeasy/domain/child/dto/request/ChildRequestDTO.java
  src/main/java/final_project/momeasy/domain/child/dto/response/ChildResponseDTO.java
  src/main/java/final_project/momeasy/domain/child/entity/Child.java
  src/main/java/final_project/momeasy/domain/child/exception/ChildErrorCode.java
  src/main/java/final_project/momeasy/domain/child/repository/ChildRepository.java
  src/main/java/final_project/momeasy/domain/child/service/command/ChildCommandService.java
  src/main/java/final_project/momeasy/domain/child/service/command/ChildCommandServiceImpl.java
  src/main/java/final_project/momeasy/domain/child/service/query/ChildQueryService.java
  src/main/java/final_project/momeasy/domain/child/service/query/ChildQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/illness/entity/Illness.java
  src/main/java/final_project/momeasy/domain/illness/repository/IllnessRepository.java
  src/main/java/final_project/momeasy/domain/parent/controller/ParentController.java
  src/main/java/final_project/momeasy/domain/parent/entity/Parent.java
  src/main/java/final_project/momeasy/domain/parent/entity/ParentChild.java
  src/main/java/final_project/momeasy/domain/parent/repository/ParentRepository.java
  src/main/java/final_project/momeasy/domain/parent/service/command/ParentCommandService.java
  src/main/java/final_project/momeasy/domain/parent/service/command/ParentCommandServiceImpl.java
Labels: ✨ Feature

#67 🐛 Fix: 로그인/로그아웃 엔드포인트 수정
  src/main/java/final_project/momeasy/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#82 ✨ [FEAT] 임베디드 온습도, 체온 센서 데이터 저장
  src/main/java/final_project/momeasy/domain/child/repository/ChildRepository.java
  src/main/java/final_project/momeasy/domain/fever_record/service/FeverRecordService.java
  src/main/java/final_project/momeasy/domain/home_cam/converter/HomecamConverter.java
  src/main/java/final_project/momeasy/domain/home_cam/entity/Homecam.java
  src/main/java/final_project/momeasy/domain/home_cam/repository/HomecamRepository.java
  src/main/java/final_project/momeasy/domain/home_cam/service/HomecamServiceImpl.java
  src/main/java/final_project/momeasy/domain/room_condition/service/RoomConditionService.java
  src/main/java/final_project/momeasy/global/tcp/SensorDataQueue.java
  src/main/java/final_project/momeasy/global/tcp/TcpServer.java
Labels: ✨ Feature

#84 ✨ [FEAT] 온도, 습도, 체온 그래프 엔티티 생성 / 발열 리포트에 그래프 기능 추가
  src/main/java/final_project/momeasy/common/enums/DayRange.java
  src/main/java/final_project/momeasy/domain/fever_graph/converter/FeverGraphConverter.java
  src/main/java/final_project/momeasy/domain/fever_graph/dto/FeverGraphResponseDTO.java
  src/main/java/final_project/momeasy/domain/fever_graph/entity/FeverGraph.java
  src/main/java/final_project/momeasy/domain/fever_graph/exception/FeverGraphErrorCode.java
  src/main/java/final_project/momeasy/domain/fever_graph/exception/FeverGraphException.java
  src/main/java/final_project/momeasy/domain/fever_graph/repository/FeverGraphRepository.java
  src/main/java/final_project/momeasy/domain/fever_graph/service/AvgFever.java
  src/main/java/final_project/momeasy/domain/fever_graph/service/FeverGraphService.java
  src/main/java/final_project/momeasy/domain/fever_graph/service/FeverGraphServiceImpl.java
  src/main/java/final_project/momeasy/domain/fever_record/repository/FeverRecordRepository.java
  src/main/java/final_project/momeasy/domain/fever_report/controller/FeverReportController.java
  src/main/java/final_project/momeasy/domain/fever_report/converter/FeverReportConverter.java
  src/main/java/final_project/momeasy/domain/fever_report/dto/FeverReportResponseDTO.java
  src/main/java/final_project/momeasy/domain/fever_report/entity/FeverReport.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportQueryService.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportQueryServiceImpl.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportService.java
  src/main/java/final_project/momeasy/domain/fever_report/service/FeverReportServiceImpl.java
  src/main/java/final_project/momeasy/domain/humidity_graph/converter/HumidityGraphConverter.java
  src/main/java/final_project/momeasy/domain/humidity_graph/dto/HumidityGraphResponseDTO.java
  src/main/java/final_project/momeasy/domain/humidity_graph/entity/HumidityGraph.java
  src/main/java/final_project/momeasy/domain/humidity_graph/exception/HumidityGraphErrorCode.java
  src/main/java/final_project/momeasy/domain/humidity_graph/exception/HumidityGraphException.java
  src/main/java/final_project/momeasy/domain/humidity_graph/repository/HumidityGraphRepositoy.java
  src/main/java/final_project/momeasy/domain/humidity_graph/service/AvgHumidity.java
  src/main/java/final_project/momeasy/domain/humidity_graph/service/HumidityGraphService.java
  src/main/java/final_project/momeasy/domain/humidity_graph/service/HumidityGraphServiceImpl.java
  src/main/java/final_project/momeasy/domain/room_condition/repository/RoomConditionRepository.java
  src/main/java/final_project/momeasy/domain/temperature_graph/converter/TemperatureGraphConverter.java
  src/main/java/final_project/momeasy/domain/temperature_graph/dto/TemperatureGraphResponseDTO.java
  src/main/java/final_project/momeasy/domain/temperature_graph/entity/TemperatureGraph.java
  src/main/java/final_project/momeasy/domain/temperature_graph/exception/TemperatureGraphErrorCode.java
  src/main/java/final_project/momeasy/domain/temperature_graph/exception/TemperatureGraphException.java
  src/main/java/final_project/momeasy/domain/temperature_graph/repository/TemperatureGraphRepository.java
  src/main/java/final_project/momeasy/domain/temperature_graph/service/AvgTemperature.java
  src/main/java/final_project/momeasy/domain/temperature_graph/service/TemperatureGraphService.java
  src/main/java/final_project/momeasy/domain/temperature_graph/service/TemperatureGraphServiceImpl.java
  src/main/java/final_project/momeasy/global/tcp/TcpServer.java
Labels: ✨ Feature
